-- MySQL Script generated by MySQL Workbench
-- Sex 11 Mai 2018 14:28:37 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`endereco` (
  `cpf` VARCHAR(11) NOT NULL,
  `rua` VARCHAR(45) NULL,
  `numero` INT NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cpf`, `cep`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`eleitores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`eleitores` (
  `id_eleitor` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `data_nascimento` VARCHAR(45) NULL,
  `telefone_celular` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NULL,
  `zona` VARCHAR(45) NULL,
  `votou` TINYINT NULL,
  `digital` VARCHAR(255) NULL,
  PRIMARY KEY (`id_eleitor`, `cpf`),
  INDEX `fk_eleitores_1_idx` (`cep` ASC),
  CONSTRAINT `fk_eleitores_1`
    FOREIGN KEY (`cep`)
    REFERENCES `mydb`.`endereco` (`cep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
